# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iTunesAlbum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunesAlbum
  pod 'SQLite.swift', '~> 0.14.0'

end
